---
- name: "install mariadb"
  hosts: db
  remote_user: vagrant
  roles:
     - mariadb
     - collect


- name: "install db  central"
  hosts: central
  remote_user: vagrant
  roles:
    - central

      

