---
# tasks file for roles/central


- name : "[CENTRAL] - apt-get update"
  become: yes
  apt:
    update_cache: yes


- name : "[CENTRAL] - install"
  become: yes
  apt:
    name: "{{ maria_packages }}"

- name : "[CENTRAL] - start service11"
  become: yes
  service:
    name: mysql
    state: started


- name : "[CENTRAL] - install DB"
  become: yes
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ maria_databases }}"

- name: "[CENTRAL] - change my.cnf"
  become: yes
  lineinfile:
    dest: "/etc/mysql/my.cnf"
    line: "{{ item }}"
  with_items:
    - "[mysqld]"
    - "bind-address  = 0.0.0.0"
    - "# skip-networking"
  notify: maria_restart

- name: "[CENTRAL] - create user"
  become: yes
  mysql_user:
    name: "{{ maria_user }}"
    password: "{{ maria_pwd }}"
    priv: "*.*:ALL"
    host: "%"

- name: "[CENTRAL] - restart"
  become: yes
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: "[CENTRAL] - create directory"
  become: yes
  file:
    path: /opt/central/
    state: directory
    mode: 0755

- name: "[CENTRAL] - copy file appli"
  become: yes
  copy:
    src: central.py
    dest: /opt/central/central.py
    mode: 0755

- name: "[CENTRAL] - create directory"
  become: yes
  file:
    path: /var/central
    state: directory
    mode: 0755

- name: "[CENTRAL] - copy file service"
  become: yes
  copy:
    src: central.service
    dest: /etc/systemd/system/central.service
    mode: 0755

- name: "[CENTRAL] - start service1 central"
  become: yes
  service:
    name: central
    state: started

