---
<<<<<<< HEAD
 - name: "[mariadb]- update os"
   become: yes
   apt: update_cache=yes
   tags: update

 - name: "[mariadb]- install "
   become: yes
   apt:   name={{ item }}
   with_items:
      - software-properties-common
      - mariadb-server
      - mariadb-client
      - python-mysqldb

# - systemd:
#        name: mariadb
#        state: restarted

 - name: "[mariadb]- start service1"
   become: yes
   service: name=mariadb  state=started

 - name: "[mariadb]- install DB"
   become: yes
   mysql_db: name={{ item }} state=present 
   with_items: 
        - yata1
        - yata2
        - yata3
 
 - name: "[mariadb]- change my.cnf"
   become: yes
   lineinfile: dest="/etc/mysql/my.cnf" line={{ item }}
   with_items: 
      - "[mysqld]"
      - "bind-address = 0.0.0.0"
      - "# skip-networking"
   notify: maria_restart

 - name: "[mariadb]- create user"
   become: yes
   mysql_user:
      name: yata
      password: yata
      priv: "*.*:ALL"
      host: "%"
 - name: "[mariadb]- restart"
   become: yes
   service: name=mariadb state=restarted enabled=yes
=======
# tasks file for mariadb
- name : "[MARIA] - apt-get update"
  become: yes
  apt:
    update_cache: yes


- name : "[MARIA] - install"
  become: yes
  apt:
    name: "{{ maria_packages }}"

- name : "[MARIA] - start service"
  become: yes
  service:
    name: mysql
    state: started


- name : "[MARIA] - install DB"
  become: yes
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ maria_databases }}"

- name: "[MARIA] - change my.cnf"
  become: yes
  lineinfile:
    dest: "/etc/mysql/my.cnf"
    line: "{{ item }}"
  with_items:
    - "[mysqld]"
    - "bind-address  = 0.0.0.0"
    - "# skip-networking"
  notify: maria_restart

- name: "[MARIA] - create user"
  become: yes
  mysql_user:
    name: "{{ maria_user }}"
    password: "{{ maria_pwd }}"
    priv: "*.*:ALL"
    host: "%"

- name: "[MARIA] - restart"
  become: yes
  service:
    name: mysql
    state: restarted
    enabled: yes

>>>>>>> ae33c2f28f30053aa092fe5405c1de9954312802
